
filebeat.inputs:

  - type: log
    enabled: true
    paths:
      - /var/log/trace-log-collector/*.log

    fields:
      log_topic: my-replicated-topic
      #这里必须是正则\. 否则不监控任何文件
      #提示如下信息是正常
      #2019-03-06T14:33:26.128+0800	INFO	log/harvester.go:255	Harvester started for file: /var/log/trace-log-collector/boss_info.log
      #2019-03-06T14:33:26.128+0800	INFO	log/harvester.go:255	Harvester started for file: /var/log/trace-log-collector/boss_error.log
      #ctrl+c 停掉后，能ps 出进程，但该进程已经不工作了
      #不允许双引号
    exclude_files: ['trace\.log','stdout\.log']
    include_lines: ['\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}']
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}'
      negate: true
      match: after
      max_lines: 500
      timeout: 5s
    ignore_older: 2h
    close_older: 1h
    scan_frequency: 10s
    harvester_buffer_size: 16384
    max_bytes: 10485760
    backoff: 1s
    max_backoff: 10s
    backoff_factor: 2

#processors:
#  - drop_fields:
#      fields: ["beat", "input", "source", "offset","prospector","log","timestamp","@metadata"]

#name: "host-name and can modify"

#----------------------------- kafka output --------------------------------
output.kafka:
  enabled: true
  hosts: ["192.168.1.196:9092", "192.168.1.197:9092", "192.168.1.198:9092"]
  topic: '%{[fields][log_topic]}'
  partition.round_robin:
    reachable_only: true
  worker: 2
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  codec.format:
    string: '%{[source]} %{[host.name]} %{[message]}'
